services:
  app:
    build: 
      context: .
    volumes: 
      - ../workspace:/workspace
    tty: true
    user: utakata
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data: /var/lib/postgresql/data
    enviroment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  postgres-data